### PR TITLE
Allow to be used with Symfony 5 and PHP 7.3/7.4

### PR DESCRIPTION
**Pull request by dkreuer**

### CODE REVIEW

**Comment by gino** [comment]
Is there a reason why this PR is not getting merged? I am having issues with Symfony 5, trying to get Xsolla into Laravel.

**Comment by dkreuer** [comment]
I don’t know, except that I have troubles running the tests, so I can’t prove that it works. It should.

**Comment by ghostzero** [comment]
@dkreuer checkout xsolla/xsolla-sdk-php:^4.1.0, i also did a PR that got into master to support php:^7.4 & laravel/framework:^7.0. See: #81 (& #82)

**Comment by dkreuer** [comment]
Unfortunately the mentioned PR allows PHP only up to 7.4.5. all bugfix releases of a PHP minor version should be good to be used as this is the BC promise PHP gives. Additionally I don‘t see any test coverage for 7.4.x there but hey, if the maintainers accept it that way 🤷‍♂️.

I tend to close this PR as I don’t have the time to keep it up (and we stepped away from Xsolla for now). Yes, mainly because of the compatibility issues.

**Comment by dkreuer** [comment]
I decided to close the PR since there is no response from the project maintainers.

**Pull request closed without merging**
